import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/css/globals.scss";
import pageBg from "../assets/images/page_bg.png";
import { CSSProperties } from "react";

const backgroundStyle: CSSProperties = {
    backgroundImage: `url(${pageBg.src})`,
    backgroundPosition: 'center',
    backgroundSize: '100% auto',
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Vertiflora",
    description: "Generated by create next app",
};

const StyleSheets = () => {
    return (<>
        <link href="https://api.fontshare.com/v2/css?f[]=tanker@400&display=swap" rel="stylesheet" />
        <link href="https://db.onlinewebfonts.com/c/ff43ca80668e47a1b1208ba9aed65ad2?family=Sharp+Grotesk+Medium+20+Regular" rel="stylesheet" />
        <link href="https://db.onlinewebfonts.com/c/629ed6829f706958b9bdf4f6300dfca0?family=Sharp+Grotesk+SmBold+20+Regular" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    </>)
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <StyleSheets />
            </head>
            <body style={backgroundStyle} className={inter.className}>{children}</body>
        </html>
    );
}
