import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/css/globals.scss";
import pageBg from "../assets/images/page_bg.png";
import { CSSProperties } from "react";

const backgroundStyle:CSSProperties = { 
    backgroundImage: `url(${pageBg.src})`,
    backgroundPosition: 'center',
    backgroundSize: '100% auto',
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Vertiflora",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link href="https://api.fontshare.com/v2/css?f[]=tanker@400&display=swap" rel="stylesheet" />
                <link href="https://db.onlinewebfonts.com/c/ff43ca80668e47a1b1208ba9aed65ad2?family=Sharp+Grotesk+Medium+20+Regular" rel="stylesheet"></link>
            </head>
            <body style={backgroundStyle} className={inter.className}>{children}</body>
        </html>
    );
}
